force-app/main/default/objects/Data_Object__c/Data_Object__c.object-meta.xml
<CustomObject>
    <label>Data Object</label>
    <nameField>
        <label>Data Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Object__c/fields/Custom__c.field-meta.xml
<CustomField>
    <fullName>Custom__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Returns true if the object is a custom object, false if it is a standard object.</description>
    <inlineHelpText>Returns true if the object is a custom object, false if it is a standard object.</inlineHelpText>
    <label>Custom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Custom_Setting__c.field-meta.xml
<CustomField>
    <fullName>Custom_Setting__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Returns true if the object is a custom setting, false otherwise.</description>
    <inlineHelpText>Returns true if the object is a custom setting, false otherwise.</inlineHelpText>
    <label>Custom Setting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Feed_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Feed_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Returns true if Chatter feeds are enabled for the object, false otherwise. This method is only available for Apex classes and triggers saved using SalesforceAPI version 19.0 and later.</description>
    <inlineHelpText>Returns true if Chatter feeds are enabled for the object, false otherwise. This method is only available for Apex classes and triggers saved using SalesforceAPI version 19.0 and later.</inlineHelpText>
    <label>Feed Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Has_Subtypes__c.field-meta.xml
<CustomField>
    <fullName>Has_Subtypes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the object has subtypes. The Account object, which has subtype PersonAccount, is the only object that will return true.</description>
    <inlineHelpText>Indicates whether the object has subtypes. The Account object, which has subtype PersonAccount, is the only object that will return true.</inlineHelpText>
    <label>Has Subtypes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Returns the object&apos;s label, which may or may not match the object name.</description>
    <inlineHelpText>Returns the object&apos;s label, which may or may not match the object name.</inlineHelpText>
    <label>Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Label_Plural__c.field-meta.xml
<CustomField>
    <fullName>Label_Plural__c</fullName>
    <description>Returns the object&apos;s plural label, which may or may not match the object name.</description>
    <inlineHelpText>Returns the object&apos;s plural label, which may or may not match the object name.</inlineHelpText>
    <label>Label Plural</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Mergeable__c.field-meta.xml
<CustomField>
    <fullName>Mergeable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Returns true if the object can be merged with other objects of its type by the current user, false otherwise. true is returned for leads, contacts, and accounts.</description>
    <inlineHelpText>Returns true if the object can be merged with other objects of its type by the current user, false otherwise. true is returned for leads, contacts, and accounts.</inlineHelpText>
    <label>Mergeable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <description>Three-character prefix code for the object. Record IDs are prefixed with three-character codes that specify the type of the object (for example, accounts have a prefix of 001 and opportunities have a prefix of 006).</description>
    <inlineHelpText>Three-character prefix code for the object. Record IDs are prefixed with three-character codes that specify the type of the object (for example, accounts have a prefix of 001 and opportunities have a prefix of 006)</inlineHelpText>
    <label>Prefix</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Record_Type_Dev_Names__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Dev_Names__c</fullName>
    <description>Record Type developer names</description>
    <inlineHelpText>Record Type developer names</inlineHelpText>
    <label>Record Type Dev Names</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Object__c/fields/Record_Type_Names__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Names__c</fullName>
    <description>Record Type Labels</description>
    <inlineHelpText>Record Type Labels</inlineHelpText>
    <label>Record Type Names</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DataDictionaryObjects_Batch.cls
public class DataDictionaryObjects_Batch implements Database.Batchable<SObjectType>, Database.Stateful {

    //setup stateful - get the current list of DataObjects to check against changes, get
    private List<Data_Object__c> currentDataObjectList = new List<Data_Object__c> ([Select Custom__c, Custom_Setting__c, Feed_Enabled__c, 
                                                                             Has_Subtypes__c, Label_Plural__c, Mergeable__c, 
                                                                             Name, Record_Type_Dev_Names__c, Record_Type_Names__c 
                                                                             from Data_Object__c]);
    private List<String> currentObjectNamesList = new List<String>();//used to compare for changes
    private Map<String, Data_Object__c> currentObjMap = new Map<String, Data_Object__c>();
    
    public Iterable<SObjectType> start(Database.BatchableContext bc){
        //put all current object records into map and list
        for(Data_Object__c objects : currentDataObjectList){
            currentObjectNamesList.add(objects.Name);
            currentObjMap.put(objects.Name, objects);
        }
        return Schema.getGlobalDescribe().values();//grab full all object describes
    }
    
    public void execute(Database.BatchableContext bc, List<SObjectType> scope){
        
        List<Data_Object__c> newDataObjectList = new List<Data_Object__c>();
	    List<Data_Object__c> updatedDataObjectList = new List<Data_Object__c>();
        //Loop through all the SObjectTypes
        for ( Schema.SObjectType typ : scope ) {
            String sobjName = String.valueOf(typ);
            Schema.DescribeSObjectResult objectResult = typ.getDescribe();//get describe of object
            //put 
            Boolean custom = objectResult.isCustom();
            Boolean customSetting = objectResult.isCustomSetting();
            Boolean feedEnabled = objectResult.isFeedEnabled();
            Boolean hasSubTypes = objectResult.getHasSubTypes();
            String labelPlural = objectResult.getLabelPlural();
            Boolean mergeable = objectResult.isMergeable();
            String prefix = objectResult.getKeyPrefix();
            String label = objectResult.getLabel();
            String name = objectResult.getName();
            list<Schema.RecordTypeInfo> objectRecordTypeInfoList = new list<Schema.RecordTypeInfo>();
            objectRecordTypeInfoList = objectResult.getRecordTypeInfos();//get recordtypeinfo
            String recordtypename;
            String recordtypedevname;
            Integer c = 0;
            List<String> recordTypeNameList = new List<String>();
            List<String> recordTypeDevNameList = new List<String>();
            
            //Loop record Type info and create get record type name and dev name
            for(Schema.RecordTypeInfo objectRecordTypeInfo : objectRecordTypeInfoList){
                recordTypeNameList.add(objectRecordTypeInfo.getName());
                recordTypeDevNameList.add(objectRecordTypeInfo.getDeveloperName());
                
            }
            //join record type lists into a string
            recordtypename = String.join(recordTypeNameList, ', ');
            recordtypedevname = String.join(recordTypeDevNameList, ', ');
            
            //get record and check for any updates
            if(currentObjectNamesList.contains(sobjName)){
                Data_Object__c checkObjectUpdate = currentObjMap.get(sobjName);
                //remove record from map if any are remaining then the objects have been deleted
                currentObjMap.remove(sobjName);
                //check if there are any changes/updates
                if(checkObjectUpdate.Custom__c != custom
                   || checkObjectUpdate.Custom_Setting__c != customSetting
                   || checkObjectUpdate.Feed_Enabled__c != feedEnabled
                   || checkObjectUpdate.Has_Subtypes__c != hasSubTypes
                   || checkObjectUpdate.Label_Plural__c != labelPlural
                   || checkObjectUpdate.Mergeable__c != mergeable
                   || checkObjectUpdate.Record_Type_Dev_Names__c != recordtypedevname 
                   || checkObjectUpdate.Record_Type_Names__c != recordtypename){
                       checkObjectUpdate.Custom__c = custom;
                       checkObjectUpdate.Custom_Setting__c = customSetting;
                       checkObjectUpdate.Feed_Enabled__c = feedEnabled;
                       checkObjectUpdate.Has_Subtypes__c = hasSubTypes;
                       checkObjectUpdate.Label_Plural__c = labelPlural;
                       checkObjectUpdate.Mergeable__c = mergeable;
                    checkObjectUpdate.Record_Type_Dev_Names__c = recordtypedevname;
                    checkObjectUpdate.Record_Type_Names__c = recordtypename;
                    updatedDataObjectList.add(checkObjectUpdate);
                }
            }else{
                //create a new Data Object record
                Data_Object__c newObject = new Data_Object__c(
                    Custom__c = custom,
                    Custom_Setting__c = customSetting,
                    Feed_Enabled__c = feedEnabled,
                    Has_Subtypes__c = hasSubTypes,
                    Label_Plural__c = labelPlural,
                    Mergeable__c = mergeable,
                    Name = name,
                    Prefix__c = prefix,
                    Record_Type_Names__c = recordtypename,
                    Record_Type_Dev_Names__c = recordtypedevname,
                    Label__c = label
                );
                newDataObjectList.add(newObject);
            }
        }
        insert newDataObjectList;
        update updatedDataObjectList;
    }
    
    public void finish(Database.BatchableContext bc){
        
        delete currentObjMap.values();
        DataDictionaryFields_Batch DDFB = new DataDictionaryFields_Batch();//batch for creating all field records
        Id batchId = Database.executeBatch(DDFB);
    }
}